name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-production
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_VAR_alert_email: ${{ secrets.TF_VAR_alert_email }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::927678863298:role/agriculture-data-pipeline-github-actions-role
          role-session-name: TerraformDeploy
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan